### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tetraphobia** [r3valkyrie/dnd5gen#1]
I'm going to be working on just SRD content for now, then I'll consider more options.

Character classes:
- [ ] Barbarian
- [ ] Bard
- [ ] Cleric
- [ ] Druid
- [x] Fighter
- [ ] Monk
- [ ] Paladin
- [ ] Ranger
- [ ] Rogue
- [ ] Sorcerer
- [ ] Warlock
- [ ] Wizard

Backgrounds:
- [x] Acolyte
- [x] Folk Hero
- [x] Noble
- [x] Sage
- [x] Soldier

Races:
- [x] Dragonborn
- [ ] Dwarf
- [ ] Elf
- [ ] Gnome
- [ ] Half-Elf
- [ ] Half-Orc
- [ ] Halfling
- [x] Human
- [ ] Tiefling

Additional features:
- [x] Subclasses.
- [x] Subraces.
- [x] Higher level characters.
- [ ] Manual settings.
- [ ] Output to pdf.
- [ ] Output to roll20 json.
- [ ] Calculate AC based on armor and dex modifier.
- [x] Finish CONTRIBUTING.md
